version: "2"
# NB: the html mount point must be writable for the userspice container, so it can copy in the UserSpice template files
# NB: the userspice service name (or network alias) should match the hostname in init.php ('userspice' by default) for db connections

services:
  userspice:
    image: jtullett/userspice-db:v5
    hostname: userspice-db
    ports:
      - "3306"
    volumes:
      - ./www/html/UserSpice/:/usr/share/nginx/html/UserSpice/

  www:
    depends_on:
      - userspice
    image: nginx:latest
    ports:
      - 8080:80
    volumes_from:
      - userspice
    volumes:
      - ./www/html/:/usr/share/nginx/html/
